---
- name: Disable manage_etc_hosts in /etc/cloud/cloud.cfg
  replace:
    path: /etc/cloud/cloud.cfg
    regexp: '(.*manage_etc_hosts.*)'
    replace: '#\1'

- name: Get short hostname
  command: hostname -s
  register: sap_short_hostname
  changed_when: False

#1054467 - Local host name refers to loopback address
- name: Disable default hostname resolve to loopback address
  replace:
    path: /etc/hosts
    regexp: "^(?!{{ ansible_default_ipv4.address }}.*{{ sap_short_hostname.stdout }})(.*)({{ sap_short_hostname.stdout }}.*)"
    replace: '\1'
...
