language: go
before_install:
- git config --global url.ssh://git@github.ibm.com/.insteadOf https://github.ibm.com/
- go env -w GOPRIVATE=github.ibm.com/*
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
env:
  global:
  - tf_version=0.15.0
  - PUBLIC_REPO=
stages:
- test
jobs:
  include:
  - stage: test
    if: type = pull_request AND branch != master
    go: 1.16.x
    script: go test ./... -p 1 -v -short
  - if: (branch = master) OR (tag IS present)
    go: 1.16.x
    script: go test ./... -p 1 -v -timeout 1h
deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
