---
# Storage sizing
# https://cloud.ibm.com/docs/sap?topic=sap-hana-iaas-offerings-profiles-intel-vs-vpc (Last updated 2023-12-28)
# https://cloud.ibm.com/docs/sap?topic=sap-storage-design-considerations#hana-iaas-mx2-16x128-32x256-configure (Last updated 2024-01-25)
# https://cloud.ibm.com/docs/sap?topic=sap-storage-design-considerations#hana-iaas-mx2-48x384-configure (Last updated 2024-01-25)
# https://cloud.ibm.com/docs/sap?topic=sap-hana-iaas-offerings-profiles-intel-bm-vpc (Last updated 2024-05-13)
# 
# SAP Notes:
# - 2927211 - SAP Applications on IBM Cloud Virtual Private Cloud (VPC) Infrastructure environment (v46)
# - 2779331 - HANA services use large SWAP memory (v5)
# LVM physical extent size - https://community.sap.com/t5/additional-blogs-by-sap/using-lvm-for-more-flexibility/ba-p/12871196

- name: Set default JSON file
  set_fact:
    hana_vol_setup_json: "hana_vm_volume_layout.json"

- name: Get the appropriate JSON file
  set_fact:
    hana_vol_setup_json: "hana_bm_volume_layout.json"
  when: "'-metal-' in hana_profile"

- name: Check if the JSON file for SAP HANA storage configuration is available on Ansible controller
  stat:
    path: "{{ playbook_dir }}/{{ hana_vol_setup_json }}"
  register: json_storage_file_status
  delegate_to: localhost

- name: Fail if the JSON file is missing
  fail:
    msg: "The file {{ playbook_dir }}/{{ hana_vol_setup_json }} is missing."
  when: not json_storage_file_status.stat.exists

- name: Get the JSON file content
  shell: "cat {{ playbook_dir }}/{{ hana_vol_setup_json }}"
  register: result
  changed_when: false
  when: json_storage_file_status.stat.exists
  delegate_to: localhost

- name: Save the JSON data to a variable as a fact
  set_fact:
    jsondata: "{{ result.stdout | from_json }}"

- name: Check if the chosen profile is certified for HANA VSIs
  fail:
    msg: "The chosen profile {{ hana_profile }} is not certified for HANA VSIs."
  when: hana_profile not in jsondata.profiles.keys()

- name: Detect the appropriate disks to be configured
  set_fact:
    final_storage: "{{ [jsondata, ansible_devices, hana_profile] | list | storagedetails }}"

- name: Get the missing disks
  fail:
    msg: "{{ final_storage }}"
  when: final_storage is not mapping

- name: Display final_storage
  debug:
    var: final_storage

- name: Create the volume groups
  lvg:
    vg: "{{ hana_sid | lower }}_{{ stg_details.value.lvm.vg.vg_name }}"
    pvs: "{{ stg_details.value.device | join(',') }}"
  loop: "{{ final_storage | dict2items }}"
  loop_control:
    loop_var: stg_details
  when: '"lvm" in stg_details.value.keys()'

- name: Create the logical volumes
  lvol:
    vg: "{{ hana_sid|lower }}_{{ lvm_data[0]['vg_name'] }}"
    lv: "{{ hana_sid|lower }}_{{ lvm_data[0]['lv_name'] }}"
    size: "{{ lvm_data[0]['lv_size'] }}"
    opts: "{{ lvm_data[0]['lv_options'] }}"
    shrink: false
  loop: "{{ final_storage | lvmdata }}"
  loop_control:
    loop_var: lvm_data

- name: Create the partitions
  parted:
    device: "{{ part[0] }}"
    number: 1
    label: gpt
    state: present
  loop: "{{ final_storage | partitionlist }}"
  loop_control:
    loop_var: part

- name: Create the filesystems
  filesystem:
    fstype: "{{ fs_data[0]['fs_type'] }}"
    dev: "{{ fs_data[0]['fs_device'] }}"
    opts: "{{ fs_data[0]['fs_options'] }}"
  loop: "{{ [final_storage, hana_sid | lower] | filesystemdata }}"
  loop_control:
    loop_var: fs_data

- name: Mount the filesystems
  mount:
    path: "{{ mp_data[0]['mp'] }}"
    src: "{{ mp_data[0]['mount_source'] }}"
    fstype: "{{ mp_data[0]['fs_type'] }}"
    opts: "{{ mp_data[0]['mount_opt'] }}"
    state: mounted
  loop: "{{ [final_storage, hana_sid | lower] | filesystemdata }}"
  loop_control:
    loop_var: mp_data
  when:  mp_data[0]['mp'] != None

- name: Create /usr/sap directory on Bare Metal
  ansible.builtin.file:
    path: /usr/sap
    state: directory
    mode: '0755'
  when: "'-metal-' in hana_profile"

- name: Create SWAP on Bare Metal
  ansible.builtin.include_tasks:
    file: swap_bm.yml
  when: "'-metal-' in hana_profile"

- name: Create SWAP on VSI
  ansible.builtin.include_tasks:
    file: swap_vm.yml
  when: "'-metal-' not in hana_profile"
...
