--- 
- name: Get SWAP LV name
  set_fact:
    sapapp_swap_lv: "{{ sapapp_swap_data[0]['fs_device'] }}"
  loop: "{{ [sapapp_final_storage, sap_sid | lower] | filesystemdata }}"
  loop_control:
    loop_var: sapapp_swap_data

- name: Check the current SWAP size
  set_fact:
    sapapp_swap: "{{ ansible_swaptotal_mb }}"

- name: Mount SWAP volume
  command: "swapon -av {{ sapapp_swap_lv }}"
  when: sapapp_swap == 0

- name: Add SWAP device to /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: "^{{ sapapp_swap_lv }}"
    line: "{{ sapapp_swap_lv }}  swap  swap  defaults  0 0"
...
