---
- hosts: app_host
  gather_facts: yes
  pre_tasks:
    - name: Import playbook variables
      include_vars: "saps4app-vars.yml"
  roles:
    - sapbasereq
    - s4appfs
    - s4appreq
    - s4appinst
...
